export const IPC_CHANNELS = {
  PERSON: {
    CREATE: 'person:create',
    UPDATE: 'person:update',
    DELETE: 'person:delete',
    GET_BY_ID: 'person:getById',
    LIST: 'person:list',
    TOGGLE_FAVORITE: 'person:toggleFavorite',
    UPLOAD_AVATAR: 'person:uploadAvatar',
  },
  SOCIAL: {
    CREATE: 'social:create',
    UPDATE: 'social:update',
    DELETE: 'social:delete',
    LIST_BY_PERSON: 'social:listByPerson',
    SET_PRIMARY: 'social:setPrimary',
  },
  RELATION: {
    CREATE: 'relation:create',
    UPDATE: 'relation:update',
    DELETE: 'relation:delete',
    GET_PERSON_RELATIONS: 'relation:getPersonRelations',
    GET_GRAPH_DATA: 'relation:getGraphData',
    GET_INTIMACY_DISTRIBUTION: 'relation:getIntimacyDistribution',
  },
  EVENT: {
    CREATE: 'event:create',
    UPDATE: 'event:update',
    DELETE: 'event:delete',
    LIST: 'event:list',
  },
  DIARY: {
    CREATE: 'diary:create',
    UPDATE: 'diary:update',
    DELETE: 'diary:delete',
    LIST: 'diary:list',
    ANALYZE: 'diary:analyze',
  },
  PHOTO: {
    IMPORT: 'photo:import',
    DELETE: 'photo:delete',
    BATCH_DELETE: 'photo:batchDelete',
    LINK_PERSON: 'photo:linkPerson',
    GET_PERSON_PHOTOS: 'photo:getPersonPhotos',
    LIST_ALL: 'photo:listAll',
  },
  SEARCH: {
    GLOBAL: 'search:global',
    SEMANTIC: 'search:semantic',
  },
  GROUP: {
    CREATE: 'group:create',
    UPDATE: 'group:update',
    DELETE: 'group:delete',
    GET_BY_ID: 'group:getById',
    LIST: 'group:list',
    ADD_MEMBERS: 'group:addMembers',
    REMOVE_MEMBER: 'group:removeMember',
    LIST_MEMBERS: 'group:listMembers',
    LIST_PERSON_GROUPS: 'group:listPersonGroups',
  },
  TAG: {
    CREATE: 'tag:create',
    UPDATE: 'tag:update',
    DELETE: 'tag:delete',
    GET_BY_ID: 'tag:getById',
    LIST: 'tag:list',
    LIST_BY_PARENT: 'tag:listByParent',
    APPLY: 'tag:apply',
    REMOVE: 'tag:remove',
    LIST_BY_TARGET: 'tag:listByTarget',
    LIST_TARGETS: 'tag:listTargets',
  },
  AI: {
    OCR_SCAN: 'ai:ocrScan',
    DETECT_FACES: 'ai:detectFaces',
    DETECT_LOST_CONTACTS: 'ai:detectLostContacts',
    CALCULATE_INTIMACY: 'ai:calculateIntimacy',
    EXTRACT_KEYWORDS: 'ai:extractKeywords',
    ANALYZE_EMOTION: 'ai:analyzeEmotion',
    DETECT_DUPLICATES: 'ai:detectDuplicates',
    GENERATE_GROUP_SUGGESTIONS: 'ai:generateGroupSuggestions',
  },
  REMINDER: {
    CREATE: 'reminder:create',
    UPDATE: 'reminder:update',
    DELETE: 'reminder:delete',
    GET_BY_ID: 'reminder:getById',
    LIST: 'reminder:list',
    UPCOMING: 'reminder:upcoming',
  },
  INTERACTION: {
    CREATE: 'interaction:create',
    UPDATE: 'interaction:update',
    DELETE: 'interaction:delete',
    LIST: 'interaction:list',
    LIST_BY_PERSON: 'interaction:listByPerson',
    LAST_DATE: 'interaction:lastDate',
  },
  BACKUP: {
    EXPORT: 'backup:export',
    IMPORT: 'backup:import',
    LIST: 'backup:list',
  },
  IO: {
    IMPORT_VCARD: 'io:importVCard',
    IMPORT_VCARD_FILE: 'io:importVCardFile',
    EXPORT_CSV: 'io:exportCSV',
    EXPORT_JSON: 'io:exportJSON',
  },
  TEMPLATE: {
    CREATE: 'template:create',
    UPDATE: 'template:update',
    DELETE: 'template:delete',
    GET_BY_ID: 'template:getById',
    LIST: 'template:list',
  },
  APP: {
    HAS_PIN: 'app:hasPin',
    SET_PIN: 'app:setPin',
    VERIFY_PIN: 'app:verifyPin',
    GET_CONFIG: 'app:getConfig',
    SAVE_CONFIG: 'app:saveConfig',
  },
  OLLAMA: {
    DETECT: 'ollama:detect',
    LIST_MODELS: 'ollama:listModels',
  },
  SUGGESTION: {
    GENERATE: 'suggestion:generate',
  },
  PERSONALITY: {
    BUILD_PROFILE: 'personality:buildProfile',
  },
  INTIMACY_PREDICTION: {
    PREDICT: 'intimacy_prediction:predict',
  },
  BRIDGE: {
    DETECT: 'bridge:detect',
  },
  ANALYTICS: {
    GET_LIFECYCLE_DISTRIBUTION: 'analytics:getLifecycleDistribution',
    GET_MONTHLY_INTERACTION_TREND: 'analytics:getMonthlyInteractionTrend',
    GET_NETWORK_STATS: 'analytics:getNetworkStats',
    GET_TOP_PURPOSES: 'analytics:getTopPurposes',
    GET_CONTACT_GROWTH: 'analytics:getContactGrowth',
    GET_INTERACTION_HEATMAP: 'analytics:getInteractionHeatmap',
    GET_ACTIVITY_DISTRIBUTION: 'analytics:getActivityDistribution',
    GET_TOP_RELATIONSHIPS: 'analytics:getTopRelationships',
  },
  CLIPBOARD: {
    WRITE_TEXT: 'clipboard:writeText',
  },
  UPDATE: {
    CHECK: 'update:check',
    DOWNLOAD: 'update:download',
    INSTALL: 'update:install',
    CHECKING: 'update:checking',
    AVAILABLE: 'update:available',
    NOT_AVAILABLE: 'update:not-available',
    PROGRESS: 'update:progress',
    DOWNLOADED: 'update:downloaded',
    ERROR: 'update:error',
  },
  WRAPPED: {
    GENERATE: 'wrapped:generate',
  },
  MEMORY: {
    TODAY: 'memory:today',
    RANDOM: 'memory:random',
  },
  DB_ENCRYPTION: {
    CHECK_STATUS: 'db:checkEncryptionStatus',
    ENCRYPT: 'db:encrypt',
    DECRYPT: 'db:decrypt',
    CHANGE_PASSWORD: 'db:changePassword',
    TEST_KEY: 'db:testKey',
  },
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS][keyof (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]]
